
---
version: "3"
services:

  app:
    build:
      context: .
    links:
      - zalenium
      - pushgateway

  zalenium:
    image: dosel/zalenium
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # - ./videos:/home/seluser/videos
    privileged: true
    command: [ "start" ]


  pushgateway:
    image: prom/pushgateway:v0.4.0
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:v2.0.0
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/

  grafana:
    image: grafana/grafana:4.6.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  alertmanager:
    image: prom/alertmanager:v0.11.0
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

